---
- name: create group panda
  ansible.builtin.group:
    name: panda
    state: present
- name: create user panda and add to panda and sudo groups
  ansible.builtin.user:
    name: panda
    shell: /bin/bash
    groups:
      - panda
      - sudo      
- name: copy authorized_key from user vagrant
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"    
# tasks file for user
